CREATE TABLE IF NOT EXISTS enemies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  img TEXT NOT NULL,
  stats_id INT NOT NULL
)

CREATE TABLE IF NOT EXISTS game_loading (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sentence VARCHAR(100) NOT NULL
)

CREATE TABLE IF NOT EXISTS levels (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) DEFAULT NULL,
  level INT NOT NULL,
  content TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS protagonist (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  img INT NOT NULL,
  gender ENUM('MALE', 'FEMALE') NOT NULL,
  stats_id INT NOT NULL
)

CREATE TABLE IF NOT EXISTS quest(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  subTitle TEXT NOT NULL,
  Xpos INT NOT NULL DEFAULT 0,
  Ypos INT NOT NULL DEFAULT 0,
  experience INT NOT NULL DEFAULT 0,
  done TINYINT(1) NOT NULL DEFAULT 0
)

CREATE TABLE IF NOT EXISTS stats(
  id INT AUTO_INCREMENT PRIMARY KEY,
  level INT NOT NULL DEFAULT 1,
  health DECIMAL(8,2) NOT NULL DEFAULT 10.00,
  maxHealth INT NOT NULL DEFAULT 10,
  strength INT NOT NULL DEFAULT 0,
  intellect INT NOT NULL DEFAULT 0,
  dexterity INT NOT NULL DEFAULT 0,
  constitution INT NOT NULL DEFAULT 0,
  wisdom INT NOT NULL DEFAULT 0,
  experience INT NOT NULL DEFAULT 0,
  points INT NOT NULL DEFAULT 0
)